version: '3.9'

services:
  postgresql:
    image: postgres:12.9-alpine # matches version used on aws environments
    container_name: pg-meta-transaction-processor
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dimo
      - POSTGRES_PASSWORD=dimo
      - POSTGRES_DB=meta_transaction_processor
    volumes:
      - postgresdb:/var/lib/postgresql/data:delegated
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    volumes:
      # Here you mount your setup file so it will be executed
      # when the container starts
      - ./resources/scripts/init.sh:/etc/localstack/init/ready.d/script.sh
  ganache:
    image: trufflesuite/ganache
    ports:
      - "8545:8545"
    entrypoint:
      - node
      - /app/dist/node/cli.js
      - --chain.chainId=31337
      - --database.dbPath=/db
      - --miner.blockTime=1
      - --wallet.accounts=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80,10000000000000000000000
      - --wallet.accounts=0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d,10000000000000000000000
      - --wallet.accounts=0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a,10000000000000000000000
      - --wallet.accounts=0x94dbd9c58eaba7a67456e354852b5109b13271fb4e0ee6656deba44b62ab67e4,10000000000000000000000

volumes:
  postgresdb:
    driver: local
