# Same on all environments.
MONITORING_PORT: 8888

# Hardhat default port.
ETHEREUM_RPC_URL: http://127.0.0.1:8545

# Hardhat default chain id.
ETHEREUM_CHAIN_ID: 31337

# Use the next variable. Never use this in production!
PRIVATE_KEY_MODE: true

# Private key for default Hardhat account 0. Well-known.
SENDER_PRIVATE_KEY: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80

# GSN default.
CONFIRMATION_BLOCKS: 12

# Default broker port.
KAFKA_SERVERS: 127.0.0.1:9092

# Same on all environments.
TRANSACTION_REQUEST_TOPIC: topic.transaction.request.send
TRANSACTION_STATUS_TOPIC: topic.transaction.request.status
