replicaCount: 1
image:
  repository: dimozone/meta-transaction-processor
  pullPolicy: IfNotPresent
  tag: 0.1.2
cronJob:
  enabled: false
env:
  ENVIRONMENT: prod
  ETHEREUM_CHAIN_ID: 137
  CONFIRMATION_BLOCKS: 10
  PRIVATE_KEY_MODE: false
  IN_MEMORY_DB: false
  KAFKA_SERVERS: kafka-prod-dimo-kafka-kafka-brokers:9092
ingress:
  enabled: false
resources:
  limits:
    cpu: 1
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 256Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
podDisruptionBudget:
  minAvailable: 1
kafka:
  clusterName: kafka-prod-dimo-kafka
