apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "meta-transaction-processor.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  data:
  - remoteRef:
      key: {{ .Release.Namespace }}/metatx/ethereum/rpc_url
    secretKey: ETHEREUM_RPC_URL
  - remoteRef:
      key: {{ .Release.Namespace }}/metatx/aws/access_key_id
    secretKey: AWS_ACCESS_KEY_ID
  - remoteRef:
      key: {{ .Release.Namespace }}/metatx/aws/secret_access_key
    secretKey: AWS_SECRET_ACCESS_KEY
  - remoteRef:
      key: {{ .Release.Namespace }}/metatx/kms/key_id
    secretKey: KMS_KEY_ID
  - remoteRef:
      key: {{ .Release.Namespace }}/metatx/db/host
    secretKey: DB_HOST
  - remoteRef:
      key: {{ .Release.Namespace }}/metatx/db/user
    secretKey: DB_USER
  - remoteRef:
      key: {{ .Release.Namespace }}/metatx/db/pass
    secretKey: DB_PASSWORD
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager-secret-store
  target:
    name: {{ include "meta-transaction-processor.fullname" . }}-secret
    template:
      metadata: {}
