apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: {{ include "meta-transaction-processor.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  backendType: secretsManager
  data:
    - key: {{ .Release.Namespace }}/metatx/ethereum/rpc_url
      name: ETHEREUM_RPC_URL
    {{- if .Values.tmp }}
    - key: dev/metatx/aws/access_key_id
      name: AWS_ACCESS_KEY_ID
    - key: dev/metatx/aws/secret_access_key
      name: AWS_SECRET_ACCESS_KEY
    - key: dev/metatx/kms/key_id
      name: KMS_KEY_ID
    - key: tmp/metatx/db/host
      name: DB_HOST
    - key: tmp/metatx/db/user
      name: DB_USER
    - key: tmp/metatx/db/pass
      name: DB_PASSWORD
    {{- else }}
    - key: {{ .Release.Namespace }}/metatx/aws/access_key_id
      name: AWS_ACCESS_KEY_ID
    - key: {{ .Release.Namespace }}/metatx/aws/secret_access_key
      name: AWS_SECRET_ACCESS_KEY
    - key: {{ .Release.Namespace }}/metatx/kms/key_id
      name: KMS_KEY_ID
    - key: {{ .Release.Namespace }}/metatx/db/host
      name: DB_HOST
    - key: {{ .Release.Namespace }}/metatx/db/user
      name: DB_USER
    - key: {{ .Release.Namespace }}/metatx/db/pass
      name: DB_PASSWORD
    {{- end }}
